[colors.bright]
black = "#7d7a68"
blue = "#6684e1"
cyan = "#1fad83"
green = "#60ac39"
magenta = "#b854d4"
red = "#d73737"
white = "#fefbec"
yellow = "#cfb017"

[colors.cursor]
cursor = "#a6a28c"
text = "#20201d"

[colors.normal]
black = "#20201d"
blue = "#6684e1"
cyan = "#1fad83"
green = "#60ac39"
magenta = "#b854d4"
red = "#d73737"
white = "#a6a28c"
yellow = "#cfb017"

[colors.primary]
background = "#171717"
foreground = "#a6a28c"

[font]
size = 10

[font.bold]
family = "CodeNewRoman Nerd Font"
style = "Bold"

[font.italic]
family = "CodeNewRoamn Nerd Font"
style = "Italic"

[font.normal]
family = "CodeNewRoman Nerd Font"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[34~"
key = "I"
mods = "Control"
