# Colors (Aura Theme)
# Default colors
[colors.primary]
background = "#060606"
foreground = "#edecee"

# Normal colors
[colors.normal]
black   = "#110f18"
red     = "#ff6767"
green   = "#61ffca"
yellow  = "#ffca85"
blue    = "#a277ff"
magenta = "#a277ff"
cyan    = "#61ffca"
white   = "#edecee"

# Bright colors
[colors.bright]
black   = "#4d4d4d"
red     = "#ff6767"
green   = "#61ffca"
yellow  = "#ffca85"
blue    = "#a277ff"
magenta = "#a277ff"
cyan    = "#61ffca"
white   = "#edecee"

[colors.selection]
text       = "CellForeground"
background = "#29263c"

[colors.cursor]
cursor = "#FFFFFF"

[font]
size = 11

[font.bold]
family = "CodeNewRoman Nerd Font"
style = "Bold"

[font.italic]
family = "CodeNewRoamn Nerd Font"
style = "Italic"

[font.normal]
family = "CodeNewRoman Nerd Font"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[34~"
key = "I"
mods = "Control"
